name: Build Writerside Docs

on:
  workflow_call:
    inputs:
      instance:
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  pages: write
  
env:
  DOCKER_VERSION: '243.22562'
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      web-archive-file-name: ${{ steps.compute-web-archive-file-name.outputs.output }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute web archive file name
        id: compute-web-archive-file-name
        run: |
          INSTANCE=${{ inputs.instance }}
          INSTANCE_ID=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE_ID" | tr '[:lower:]' '[:upper:]')
          WEB_ARCHIVE_FILE_NAME="webHelp${INSTANCE_ID_UPPER}2-all.zip"

          echo "INSTANCE: $INSTANCE"
          echo "INSTANCE_ID: $INSTANCE_ID"
          echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
          echo "WEB_ARCHIVE_FILE_NAME: $WEB_ARCHIVE_FILE_NAME"
          
          echo "output=$WEB_ARCHIVE_FILE_NAME" >> $GITHUB_OUTPUT

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ inputs.instance }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload build results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-results
          path: |
            artifacts/${{ steps.compute-web-archive-file-name.outputs.output }}
            artifacts/report.json
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build-results
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ inputs.instance }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build-results
          path: artifacts

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq "artifacts/${{ needs.build.outputs.web-archive-file-name }}" -d site

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4